/**/callback({"meta": {
  "Cache-Control": "public, max-age=60, s-maxage=60",
  "Vary": "Accept",
  "ETag": "\"ca162898412446cc543d56adcf9ad4da5e9fa99ba2673afad4747b0e066c966e\"",
  "Last-Modified": "Fri, 14 Nov 2025 14:11:11 GMT",
  "Content-Type": "application/javascript; charset=utf-8",
  "X-GitHub-Media-Type": "github.v3; format=json",
  "status": 200,
  "X-RateLimit-Limit": "60",
  "X-RateLimit-Remaining": "58",
  "X-RateLimit-Reset": "1763151183",
  "X-RateLimit-Used": "2",
  "X-RateLimit-Resource": "core"
}, "data": {
  "id": 14579179,
  "node_id": "MDEwOlJlcG9zaXRvcnkxNDU3OTE3OQ==",
  "name": "plotly.R",
  "full_name": "plotly/plotly.R",
  "private": false,
  "owner": {
    "login": "plotly",
    "id": 5997976,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5OTc5NzY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5997976?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/plotly",
    "html_url": "https://github.com/plotly",
    "followers_url": "https://api.github.com/users/plotly/followers",
    "following_url": "https://api.github.com/users/plotly/following{/other_user}",
    "gists_url": "https://api.github.com/users/plotly/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/plotly/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/plotly/subscriptions",
    "organizations_url": "https://api.github.com/users/plotly/orgs",
    "repos_url": "https://api.github.com/users/plotly/repos",
    "events_url": "https://api.github.com/users/plotly/events{/privacy}",
    "received_events_url": "https://api.github.com/users/plotly/received_events",
    "type": "Organization",
    "user_view_type": "public",
    "site_admin": false
  },
  "html_url": "https://github.com/plotly/plotly.R",
  "description": "An interactive graphing library for R",
  "fork": false,
  "url": "https://api.github.com/repos/plotly/plotly.R",
  "forks_url": "https://api.github.com/repos/plotly/plotly.R/forks",
  "keys_url": "https://api.github.com/repos/plotly/plotly.R/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/plotly/plotly.R/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/plotly/plotly.R/teams",
  "hooks_url": "https://api.github.com/repos/plotly/plotly.R/hooks",
  "issue_events_url": "https://api.github.com/repos/plotly/plotly.R/issues/events{/number}",
  "events_url": "https://api.github.com/repos/plotly/plotly.R/events",
  "assignees_url": "https://api.github.com/repos/plotly/plotly.R/assignees{/user}",
  "branches_url": "https://api.github.com/repos/plotly/plotly.R/branches{/branch}",
  "tags_url": "https://api.github.com/repos/plotly/plotly.R/tags",
  "blobs_url": "https://api.github.com/repos/plotly/plotly.R/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/plotly/plotly.R/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/plotly/plotly.R/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/plotly/plotly.R/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/plotly/plotly.R/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/plotly/plotly.R/languages",
  "stargazers_url": "https://api.github.com/repos/plotly/plotly.R/stargazers",
  "contributors_url": "https://api.github.com/repos/plotly/plotly.R/contributors",
  "subscribers_url": "https://api.github.com/repos/plotly/plotly.R/subscribers",
  "subscription_url": "https://api.github.com/repos/plotly/plotly.R/subscription",
  "commits_url": "https://api.github.com/repos/plotly/plotly.R/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/plotly/plotly.R/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/plotly/plotly.R/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/plotly/plotly.R/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/plotly/plotly.R/contents/{+path}",
  "compare_url": "https://api.github.com/repos/plotly/plotly.R/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/plotly/plotly.R/merges",
  "archive_url": "https://api.github.com/repos/plotly/plotly.R/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/plotly/plotly.R/downloads",
  "issues_url": "https://api.github.com/repos/plotly/plotly.R/issues{/number}",
  "pulls_url": "https://api.github.com/repos/plotly/plotly.R/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/plotly/plotly.R/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/plotly/plotly.R/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/plotly/plotly.R/labels{/name}",
  "releases_url": "https://api.github.com/repos/plotly/plotly.R/releases{/id}",
  "deployments_url": "https://api.github.com/repos/plotly/plotly.R/deployments",
  "created_at": "2013-11-21T05:56:51Z",
  "updated_at": "2025-11-14T14:11:11Z",
  "pushed_at": "2025-06-30T22:44:23Z",
  "git_url": "git://github.com/plotly/plotly.R.git",
  "ssh_url": "git@github.com:plotly/plotly.R.git",
  "clone_url": "https://github.com/plotly/plotly.R.git",
  "svn_url": "https://github.com/plotly/plotly.R",
  "homepage": "https://plotly-r.com",
  "size": 117665,
  "stargazers_count": 2650,
  "watchers_count": 2650,
  "language": "R",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": true,
  "has_discussions": true,
  "forks_count": 635,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 750,
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [
    "d3js",
    "data-visualization",
    "ggplot2",
    "javascript",
    "plotly",
    "r",
    "r-package",
    "rstats",
    "shiny",
    "webgl"
  ],
  "visibility": "public",
  "forks": 635,
  "open_issues": 750,
  "watchers": 2650,
  "default_branch": "master",
  "temp_clone_token": null,
  "custom_properties": {

  },
  "organization": {
    "login": "plotly",
    "id": 5997976,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjU5OTc5NzY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5997976?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/plotly",
    "html_url": "https://github.com/plotly",
    "followers_url": "https://api.github.com/users/plotly/followers",
    "following_url": "https://api.github.com/users/plotly/following{/other_user}",
    "gists_url": "https://api.github.com/users/plotly/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/plotly/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/plotly/subscriptions",
    "organizations_url": "https://api.github.com/users/plotly/orgs",
    "repos_url": "https://api.github.com/users/plotly/repos",
    "events_url": "https://api.github.com/users/plotly/events{/privacy}",
    "received_events_url": "https://api.github.com/users/plotly/received_events",
    "type": "Organization",
    "user_view_type": "public",
    "site_admin": false
  },
  "network_count": 635,
  "subscribers_count": 107
}})
